baseURL = 'https://fiverings.photo/'
languageCode = 'en-us'
title = 'FiveRings Photography'
canonifyURLs = true
disableRSS = true
disableKinds = ["RSS", "taxonomy", "term"]

[params]
  title = 'FiveRings Photography'
  description = 'Professional photography services'
  author = 'John Benson'

[author]
  name = 'John Benson'
  email = 'john@fiverings.photo'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
